<?php
/** @var \Custom\Grid\Block\Form $block */
$model = $block->getRecord();
$formAction = $block->getUrl('custom_grid/custom/save'); // Controller URL

?>

<form action="<?= $formAction ?>" method="post" id="custom-form" name="user">
    <?= $block->getBlockHtml('formkey'); ?> <!-- CSRF protection -->

    <?php if ($model && $model->getId()): ?>
    <input type="hidden" name="entity_id" value="<?= $model->getId(); ?>">
    <?php endif; ?>

    <div class="admin__field ">
        <label class="admin__field-label" for="name"><?= __('Name') ?></label>
        <div class="admin__field-control">
            <input type="text" name="name" id="name" class="admin__control-text"
                   value="<?= $model ? $block->escapeHtml($model->getName()) : '' ?>">
            <p class="error" id="name-error"></p>
        </div>
    </div>

    <div class="admin__field">
        <label class="admin__field-label" for="address"><?= __('Address') ?></label>
        <div class="admin__field-control">
            <input type="text" name="address" id="address" class="admin__control-text"
                   value="<?= $model ? $block->escapeHtml($model->getAddress()) : '' ?>">
            <p class="error" id="address-error"></p>
        </div>
    </div>

    <div class="admin__field">
        <label class="admin__field-label" for="zip"><?= __('Zip') ?></label>
        <div class="admin__field-control">
            <input type="text" name="zip" id="zip" class="admin__control-text"
                   value="<?= $model ? $block->escapeHtml($model->getNumber()) : '' ?>">
            <p class="error" id="zip-error"></p>
        </div>
    </div>

    <div class="admin__field">
        <label class="admin__field-label" for="number"><?= __('Number') ?></label>
        <div class="admin__field-control">
            <input type="text" name="number" id="number" class="admin__control-text"
                   value="<?= $model ? $block->escapeHtml($model->getNumber()) : '' ?>">
            <p class="error" id="number-error"></p>
        </div>
    </div>

    <div class="admin__field">
        <button type="submit" class="action-primary"><?= __('Save') ?></button>
    </div>
</form>

<script>
    function validation() {
        const form = document.forms["user"];
        let isvalid = true;

        document.querySelectorAll(".error").forEach(el => {
            el.textContent = "";
        });
        const name = form["name"].value.trim();
        if (name === "") {
            document.getElementById("name-error").textContent = " Name is required.";
            isvalid = false;
        }
        const address = form["address"].value.trim();
        if (address === "") {
            document.getElementById("address-error").textContent = " address is required.";
            isvalid = false;
        }
        const zip = form["zip"].value.trim();
        if (zip === "") {
            document.getElementById("zip-error").textContent = " zip is required.";
            isvalid = false;
        }
        const number = form["number"].value.trim();
        if (number === "") {
            document.getElementById("number-error").textContent = " number is required.";
            isvalid = false;
        }
        return isvalid;
    }

    require(['jquery'], function ($) {
        $('#custom-form').on("submit", function (e) {
            if (!validation()) {
                e.preventDefault();
            }
        });
    });
</script>
